"""empty message

Revision ID: 0cfb6f0513ae
Revises: 
Create Date: 2022-01-02 23:02:25.921438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cfb6f0513ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('search', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('sort', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter')
    # ### end Alembic commands ###
